name: Core
version: 6.0.4
author: MasterDash5
description: "DashNetwork main plugin."
softdepend: [ProtocolLib, ProtocolSupport, ViaVersion, DiscordSRV]
main: dashnetwork.core.Core
api-version: 1.15

permissions:
  dashnetwork.staff:
    default: op
  dashnetwork.admin:
    default: op
  dashnetwork.owner:
    default: false

commands:
  adminchat:
    aliases: [ac]
  altspy:
  anvil:
  autowelcome:
    aliases: [autowb]
  bookspy:
    aliases: [bs]
  center:
  clearchat:
    aliases: [cc]
  clearlag:
    aliases: [cl]
  colorlist:
    aliases: [colors]
  commandspy:
    aliases: [cmdspy, cs]
  console:
  crash:
  fakejoin:
  fakeleave:
  fakeop:
  foxshot:
    aliases: [foxcannon]
  fuckoff:
  gamestate:
    aliases: [state]
  getoffme:
    aliases: [getoffofme]
  google:
  import:
  invisibility:
    aliases: [invis]
  killears:
  list:
    aliases: [online, glist]
  login:
    aliases: [register]
  lore:
    aliases: [setlore]
  mattsarmorstands:
  modlist:
    aliases: [modslist]
  mommy:
    aliases: [daddy, grandma, grandpa, aunt, uncle]
  moonphase:
    aliases: [moon]
  namemc:
    aliases: [usernamehistory, namehistory]
  nightvision:
    aliases: [nv, see]
  oplist:
    aliases: [ops]
  ownerchat:
    aliases: [oc, dc]
  peek:
  ping:
  pingspy:
  playerinfo:
  rename:
    aliases: [setname]
  respawn:
    aliases: [forcerespawn]
  ride:
    aliases: [getaride]
  server:
    aliases: [servers, world, worlds, warp, warps]
  serverinfo:
  signspy:
    aliases: [ss]
  skin:
    aliases: [setskin]
  spawn:
  spin:
  staffchat:
    aliases: [sc]
  thefurpysong:
    aliases: [furpysong]
  vanish:
    aliases: [v]
  versionlist:
    aliases: [verlist]