name: DashNetworkCore
version: 6.0.0
author: MasterDash5
description: "DashNetwork main plugin."
softdepend: [ProtocolSupport, ViaVersion]
main: dashnetwork.core.Core
api-version: 1.15

permissions:
  dashnetwork.staff:
    default: op
  dashnetwork.admin:
    default: op
  dashnetwork.owner:
    default: false

commands:
  anvil:
  center:
  clearchat:
    aliases: [cc]
  clearlag:
    aliases: [cl]
  colorlist:
    aliases: [colors]
  commandspy:
    aliases: [cmdspy, cs]
  console:
  crash:
  fakejoin:
  fakeleave:
  fakeop:
  foxshot:
    aliases: [foxcannon]
  google:
  invisibility:
    aliases: [invis]
  killears:
  list:
    aliases: [online, glist]
  login:
    aliases: [register]
  mattsarmorstands:
  modlist:
    aliases: [modslist]
  moonphase:
  nightvision:
    aliases: [nv, see]
  oplist:
    aliases: [ops]
  ping:
  spin:
  test:
  versionlist:
    aliases: [verlist]